### ISSUE TITLE
drt for multi-modal scenario

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#10]
I am trying to extend my base scenario (routed car and pt, teleported walk and bike) to incorporate drt. So far I am working from the RunDoor2DoorDrtExample, but I am crashing on:

> Supported for only 1 DRT mode in the config. Number of DRT modes: 0

As far as I can tell this might be related to the DvrpConfigGroup class for createControlerWithSingleModeDrt which does not seem compatible for multiple modes. I have also seen the MultiModeDrtConfigGroup, but this class does not have it's own controller creator. 

Could you point me in the right direction in regarding to incorporating the drt extension into my model, considering all other modes should be able to switch to drt using their ChangeTripMode strategy? 

Thanks in advance

[RunMatsim_drt.txt](https://github.com/matsim-org/matsim-maas/files/3681797/RunMatsim_drt.txt)
[Log.txt](https://github.com/matsim-org/matsim-maas/files/3681789/Log.txt)

**Comment by michalmac** [comment]
You need to adapt the config file. This change comes from this PR: https://github.com/matsim-org/matsim/pull/639

Here you can find a short hint on how to convert single to multi-mode config: https://github.com/matsim-org/matsim/pull/637#issuecomment-526348890 (it is about taxi, but replace each 'taxi' with 'drt', preserving the case)

**Comment by michalmac** [comment]
(the content of the drt config group remains the same, it is only now wrapped with the new multi-drt config)

**Comment by mr-illington** [comment]
Hi Michal, thanks for your response. I think this is a slightly different answer but it helped me find the issue:

In my previous runners I create a controller based on a scenario object, while the DrtControlerCreater class only accepts config input. Therefore the work I was doing on other scenario objects (population) was not being carried through into the controller. Thanks for your help!
