### ISSUE TITLE
event handling for drt wait times

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#13]
My current event handler was designed around a scenario prior to added drt. It of course captures drt-relevant information through the various Activity-Person-Vehicle event handlers it implements. 

But there is one metric I am looking for which I currently to not get: wait time.

I get pt wait times through the `AgentWaitingForPtEventHandler`, but I'm wondering if there something similar for drt? My goal is to get wait times on an agent-level so more detailed than what is provided in the `drt_customer_stats_drt.csv` output. 

Thanks in advance!

**Comment by jfbischoff** [comment]
The easiest to track waiting times for DRT is to measure the time between the departure event and the PersonEntersVehicle event. This should do the trick :)

**Comment by mr-illington** [comment]
I don't know why I did not think of that as it's the exact workflow I already implement for the other trip segments. Got it now, thanks!
