### ISSUE TITLE
Sharaeble av fleet with congestion pricing network

### ISSUE THREAD

**Issue by rutym** [matsim-org/matsim-maas#16]
Hi all.
My research focus is the combination between shareable av taxis (=multiple passengers in a single ride) and a network with dynamic congestion pricing.
In the past couple of weeks I've played with the example scenarios in the DRT contrib library, read Matsim's manual and looked at the implementation code. Before I continue, I have few questions I hope you could help me with:

1.  Adding dynamic congestion to the DRT mode:
I'm interested in adding a dynamic congestion toll to links, similar to what is done in the ['decongestion' contrib library](https://github.com/matsim-org/matsim/tree/master/contribs/decongestion). My main concern is that the 'decongestion' contribution updates the prices on links between each iteration, but the shareable av fleet DRT contribution uses only a single iteration (due to using dynamic agents). Is there another way to include congestion pricing on the links, that is not fixed? (i.e., I do not want to set up fixed tolls on the links in the 'network' configuration file.)

2. Dispatching algorithm:
I'm interested in checking a few different dispatching algorithms for the fleet.  Horl el al. have done something similar using AMod([Fleet operational policies for automated mobility: A simulation
assessment for Zurich](https://www.sciencedirect.com/science/article/pii/S0968090X18304248)), and I was wondering if I can implement this in Matsim.
I've seen the correspondence in the ['Taxi Contribution: alternative taxi assignment algorithms available?'](https://github.com/matsim-org/matsim-maas/issues/9), and am wondering:

- Will it be possible to test some of these dispatching algorithm solely by updating the cost function?
-  What are the complications in writing my own `DrtOptimizer`? What should I be careful of? I'm proficient in Java and have worked with the 'Guice' framework before, so I'm not afraid of getting my hands dirty.

3. Recommended case study:
Is there a recommended case study to work with? I see that the 'Berlin' case study is highly researched, but I'm wondering if maybe it has too many details, as I primarily want to focus on only av cars. On the other hand, the Sioux Falls case study looks too small.

Thanks,
Ruty

**Comment by michalmac** [comment]
Re 1: Ihab Kaddoura works on decongestion and he has also tried out combining pricing with AV. Maybe ask a question here, so he sees it and can answer: https://github.com/matsim-org/matsim-code-examples/issues

Re 2: You can modify some part of the DRT optimiser (most of the standard components can be overridden using guice). Please have a look how we adapted DRT to electric vehicles, as an example: https://github.com/matsim-org/matsim/tree/master/contribs/drt/src/main/java/org/matsim/contrib/edrt. Writing a new algorithm from scratch is possible too, but requires more work. You can find some hints in this paper: https://depositonce.tu-berlin.de//handle/11303/9138

Re 3: This is a collection of available open scenarios: https://github.com/matsim-scenarios. I suggest using those which are is actively developed. You can always downsample if computation times are too long.
