### ISSUE TITLE
Via aggregation analysis of drt wait time

### ISSUE THREAD

**Issue by mr-illington** [matsim-org/matsim-maas#17]
Hello, 

I'm trying to use Via to do spatial aggregation analysis of drt wait and in vehicle times. While I can produce this for other metrics like duration, I have yet to find wait or in vehicle tt as an attribute through the standard aggregation analysis approach. 

Is something extra required to bring dvrp-specific outputs into Via for analysis there? Is this possible?

![image](https://user-images.githubusercontent.com/17620869/69865036-88f44a80-12a0-11ea-993a-43d46adcbd05.png)

**Comment by michalmac** [comment]
Maybe @mrieser (the author of VIA) has some ideas. I think he considered adding some DRT output analysis. Not sure if it is already there.

**Comment by jfbischoff** [comment]
Hi, 
this is actually very easy:
In each iteration folder, there is a trip table of all DRT trips, including the start and end coordinates of each trip. You can pass that CSV file into VIA and then feed your aggregation analysis with it.

**Comment by mr-illington** [comment]
Great, thanks.
