### ISSUE TITLE
Error in running MATSim-MAAS example

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-maas#18]
Hello,
I am trying to replicate the MATSim-MAAS example as you have shared using COTTBUS and MIELEC data. I am using the matsim-maas-12.0-SNAPSHOT-jar-with-dependencies.jar file which is part of the example to run the scenario. However, except the MIELEC_drt other scenarios are not running. Below is the exception I receive 

`

```
> 2020-07-20T08:40:00,444  WARN PlanCalcScoreConfigGroup:193 activityType_0 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
> 2020-07-20T08:40:00,447  WARN PlanCalcScoreConfigGroup:207 activityTypicalDuration_0 is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
> 2020-07-20T08:40:00,449  WARN PlanCalcScoreConfigGroup:242 traveling_taxi is deprecated config syntax; please use the more modern hierarchical format; your output_config.xml will be in the correct version; the old version will fail eventually, since we want to reduce the workload on this backwards compatibility (look into PlanCalcScoreConfigGroup or PlanCalcRouteConfigGroup if you want to know what we mean).
> Exception in thread "main" java.lang.IllegalArgumentException: Supported for only 1 DRT mode in the config. Number of DRT modes: 0
> 	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:190)
> 	at org.matsim.contrib.drt.run.DrtConfigGroup.getSingleModeDrtConfig(DrtConfigGroup.java:56)
> 	at org.matsim.contrib.drt.run.DrtControlerCreator.createControlerWithSingleModeDrt(DrtControlerCreator.java:63)
> 	at org.matsim.maas.drt.RunDRTClass.run(RunDRTClass.java:40)
> 	at org.matsim.maas.drt.RunDRTClass.main(RunDRTClass.java:55)
> 
> The simulation did not run properly. Error/Exit code: 1
```

`

I do not understand what changes is needed on the config file to make it run. Any help would be appreciated.

**Comment by tschlenther** [comment]
Hi,
the following means that no drt module could be loaded from the config file you provided.
> > Exception in thread "main" java.lang.IllegalArgumentException: Supported for only 1 DRT mode in the config. Number of DRT modes: 0

Might be that our example files need an update, i will have a look. Can you provide information on which input files you used when this error occured? Thank you.

Best,

Tilmann

**Comment by vsgo222** [comment]
Also, I cloned the MATSim project 0.12. However, MIELEC_drt_config.xml, fails to run with same error. 
I am assuming that when I cloned the newest verson of the MATSim, the extensions available in the form of contrib will be configured internally. If not, any directions how to bring the extensions into the cloned project?

**Comment by vsgo222** [comment]
> 
> 
> Hi,
> the following means that no drt module could be loaded from the config file you provided.
> 
> > > Exception in thread "main" java.lang.IllegalArgumentException: Supported for only 1 DRT mode in the config. Number of DRT modes: 0
> 
> Might be that our example files need an update, i will have a look. Can you provide information on which input files you used when this error occured? Thank you.
> 
> Best,
> 
> Tilmann

Same error for mielec_taxi_config_assignment, mielec_taxi_config_rulebased, robotaxi_config

**Comment by tschlenther** [comment]
Hi,

the .jar in the repository is meant to work with drt only. The input files you referred to represent taxi simulations (using taxi contrib instead of drt contrib). Sorry for confusion, i will update the Readme.md and the jar's name in order to clarify this.
If you want to run one of the taxi scenarios, try running the class RunTaxiExample from your IDE. You can choose the scenario by commenting/uncommenting the lines in the main method.
