### ISSUE TITLE
how to write plan for stop based drt?

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-maas#2]
I am using following format for stop based drt plan and i am getting
 ERROR StopBasedDrtRoutingModule:120 Start and end stop are the same, agent will walk.
even when change home location in last activity type I am getting the same error.

```
<person id="1"> 
           <plan score="0.0" selected="yes">
           <activity type="home" link="3018.0" x="73.910586" y="18.566487" end_time="07:02:00"/>
           <leg mode="drt">  </leg>
           <activity type="work" link="3276.0" x="73.912336" y="18.559009"  end_time="18:42:00" />
           <leg mode="drt"> </leg>
           <activity type="home" link="3018.0" x="73.910586" y="18.566487" />
           </plan> </person>
```

**Comment by jfbischoff** [comment]
The stops need to be in the MATSim TransitSchedule-Format. Their coordinate system should match the one of the network.

**Comment by Sharmeela16** [comment]
i am using the same coordinate system format for TransitSchedule and network 
<transitSchedule>
<transitStops>
<stopFacility id="1" x="73.920791" y="18.553447" linkRefId="56" isBlocking="false" />            
<stopFacility id="2" x="73.920946" y="18.555623" linkRefId="42" isBlocking="false" />            
<stopFacility id="3" x="73.92146" y="18.558042" linkRefId="19" isBlocking="false" /> 

<nodes>
<node id="1225170943" x="73.9346605" y="18.5397562" ></node>
<node id="1225171342" x="73.9314887" y="18.5420148" ></node>
<links capperiod="01:00:00" effectivecellsize="7.5" effectivelanewidth="3.75">
<link id="1" from="2982733291" to="2984584197" length="154.198089" freespeed="4.166667" capacity="600" permlanes="1" oneway="1" modes="drt" ></link> 
<link id="10" from="1236971404" to="1801023565" length="108.534511" freespeed="4.166667" capacity="600" permlanes="1" oneway="1" modes="drt" ></link>

**Comment by michalmac** [comment]
> ERROR StopBasedDrtRoutingModule:120 Start and end stop are the same, agent will walk.
Actually this is a warning only (will change the message soon). It means that the start and end locations are so close that the agent will be picked up and dropped off at exactly the same stop.

This would not make sense at all, therefore the agent will walk directly from the start to end location. This type of warning is printed out only if `isPrintDetailedWarnings` in the DRT config group is set to `true`.

**Comment by Sharmeela16** [comment]
But I am getting this message for all the agents in the plan whose start and end locations are not nearby.
