### ISSUE TITLE
Where to Start For Using DVRP Extension

### ISSUE THREAD

**Issue by CianGraham** [matsim-org/matsim-maas#20]
Dear MAAS Team,

I currently have had built my base model in MATSim (with my network, plan, pt and other basic files). My research will be about autonomous vehicles so I would like to add SAVs into my network in the coming steps. I see most of the AV paper implemented DVRP extension but without the source codes or some examples, therefore, I can only search online, that's why I was guided here.

I see there are many different extensions available for different modules (AVs, taxis, DRT, DVRP etc.), and from what I understand they are all from the basic DVRP models. I have read through the Module introduction in the MATSim book, so I know the OneTaxiExample is a good place to get started. However, I cannot find the `configUrl` in the source code `dvrp:13.0`. Hence, my studying path gets stuck again.

I also tried to search other dvrp codes in the MATSim code example. Under the `extensions.dvrp`, I saw another class for `RunOneTaxiExample`, but this one is totally different from the one in the source code, I also cannot find the config file it refers to (like `/src/main/resources/one_taxi/one_taxi_config.xml`). So I really don't know what I should do next to continue.

Can you please offer me some suggestions regarding where I should start? And also, which extensions I should use for my research purposes? I will be very appreciated for any suggestions you offered.

Thanks,
Cian

**Comment by sinkan851014** [comment]
@CianGraham 
Deer CianGraham, Have you solved this problem yet? I'm currently trying to do the same research (on autonomous cars) and would like to know how you solved it, I have some Java basics and would appreciate it if you could provide me with a learning path!
