### ISSUE TITLE
org.matsim.run.gui does not exist

### ISSUE THREAD

**Issue by sallyqiansun** [matsim-org/matsim-maas#21]
Hi, when I was trying to run the massgui, it shows an error pointing to the line: 
`import org.matsim.run.gui.Gui;`
Could I know where the problem is? Thank you!

**Comment by mrieser** [comment]
can you please provide the full error message?
How did you start MATSim? By double-clicking the jar-file, or from the command line? If from the command line, can you please specify the exact command you used?

**Comment by sallyqiansun** [comment]
I started the MATsim gui by running java -jar matsim-12.0.jar. It worked fine with the equil example. But when I tried to run the MassGUI, the error message shows: 
/matsim-maas-master/src/main/java/org/matsim/maas/RunMaasGui.java:23:26
java: package org.matsim.run.gui does not exist

**Comment by sallyqiansun** [comment]
This issue is resolved. I found the answer here: https://github.com/matsim-org/matsim-maas/issues/14
