### ISSUE TITLE
How to interpret scores and achieve convergence?

### ISSUE THREAD

**Issue by vishalmhjn** [matsim-org/matsim-maas#3]
I am doing a study to analyse the impacts of DRT for 10% population. In the scenario **without DRT Maas**, Only cars are simulated, Convergence is fast and rush hour peaks are also very prominent, which is expected.
![20 legHistogram_car](https://user-images.githubusercontent.com/42190624/54766706-0937bb80-4bfc-11e9-8356-477a39b45f73.png)

In the **Door-2-Door DRT service** with around 1000 DRT vehicles, **Cars and DRT vehicles** are simulated and together they make up 100,000 agents with Car: DRT demand in ratio of 3:2. I am unable to get the score graph to convergence and need some help understand it. One iteration takes around 40 minutes and as you can see, the agent scores do not converge even on 100th iteration (after around 3 days)?
![scorestats (1)](https://user-images.githubusercontent.com/42190624/54766408-81ea4800-4bfb-11e9-840a-53ae2c31c747.png)

 Also the morning and evening peaks for Cars are not clearly differentiable in this case as compared to previous case. Do i need to run more iterations or any other suggestions to debug this?

TIA 

![100 legHistogram_car](https://user-images.githubusercontent.com/42190624/54766474-9af2f900-4bfb-11e9-80cf-b7be991d93cf.png)

![100 legHistogram_drt](https://user-images.githubusercontent.com/42190624/54766548-b9f18b00-4bfb-11e9-877d-ba774c8fc217.png)

**Comment by michalmac** [comment]
There may be a couple of reasons. But let's first try to collect some info:
- in the first scenario, there is about 60k car trips, and there is some congestion in the afternoon
- in the second scenario, there is 60k car trips and 40k drt trips, served by 1k vehicles (of what capacity? 2? 3?)
Is that right?

BTW. There are a couple of interesting DRT plots that could be helpful (esp. vehicle occupancy profiles and time-based drt detours). Could you upload them to give some more insight?

**Comment by michalmac** [comment]
I see that in both scenarios the total number of trips is the same. Nevertheless, looking at the departures it does not sum up to 100k trips (you mentioned about 100k agents).

**Comment by vishalmhjn** [comment]
The exact number of agents/ trips in the scenario are 105216 which comprise Cars (64158 trips) and DRT (41058 trips). Few more details on the inputs:
a) Plan creation: From the synthetic population of Car trips (105216), Random selection of trips (41058) is made and these trips are assigned to the DRT mode. Rest of the trips still use Cars (64158).
b) Vehicle capacity is 8 pax
c) Agent plans are composed of double legs (outgoing and incoming for Home-based trips) as well as single leg (only outgoing for Non-home based trips)

I checked the histogram.txt to confirm the departures. Since each double legged trip is associated with 2 departures and 2 arrivals, the numbers should make up to approximately 100k trips. There could be some inconsitency due to Cars stuck in network due to congestion and Single legged trips. I attach the histogram.txt file for more details.
[100.legHistogram.txt](https://github.com/matsim-org/matsim-maas/files/3003255/100.legHistogram.txt)

The others plots are below. 

![100 waitStats_drt](https://user-images.githubusercontent.com/42190624/54920436-89fbfd80-4f03-11e9-9b80-269a9b3fe769.png)
![100 drt_occupancy_time_profiles_StackedArea_drt](https://user-images.githubusercontent.com/42190624/54920447-91bba200-4f03-11e9-83eb-5b229e24951a.png)
![100 drt_detours_drt_travelTimePlot](https://user-images.githubusercontent.com/42190624/54920448-92543880-4f03-11e9-858e-16e421f32e02.png)
![100 drt_detours_drt_rideTimePlot](https://user-images.githubusercontent.com/42190624/54920449-92eccf00-4f03-11e9-91cb-90ca40424ffe.png)

PS: I understand my question is not very specific, but any hint/ suggestion would be immensely helpful.

**Comment by michalmac** [comment]
Thanks for the detailed description. It seems that the biggest problem is traffic congestion that cars are stuck in, while DRT buses not (only relatively few requests take longer than expected). It may sound illogical, since each DRT bus has 1.5 passengers on board around the peak hours.

The main reason is that DRT buses use a moving average of travel times (TT) over last iterations, whereas cars use TT from the very last one. What I would suggest is to try out:
1. reducing the share of DRT
2. reducing ReRoute probability (and even switching it off at some point)
3. I assume the mode choice is switched off at all -- if not, switch it off at all

Re 2. Since your initial scenario is "without DRT Maas", I would just take the output plans (after 100 iters, or so) and use them as the input for the "with DRT Maas" scenario. This is not super realistic, but keeping things less changeable from iteration to iteration should help finding the right config parameters.
