### ISSUE TITLE
how to assign minimum occupancy to vehicles?

### ISSUE THREAD

**Issue by Sharmeela16** [matsim-org/matsim-maas#5]
Is there anyway to assign minimum occupancy to DRT vehicles? so vehicles without reaching minimum occupancy will not run.

**Comment by michalmac** [comment]
You cannot directly do this as it would lead to starvation of some customers. However, the current (default) DRT algorithm focuses on minimising the vehicle mileage given that the passenger max wait/ride time constraints are satisfied. What you can do is to reduce the fleet size and increase both max time constraints. Thus you will yield much higher sharing levels, though still some vehicles may travel empty or with 1 passenger aboard.
