### ISSUE TITLE
Getting "No Zone found for linkId" error message

### ISSUE THREAD

**Issue by XXXinnnn** [matsim-org/matsim-maas#8]
I'm running the simulation with **drt zonal analysis** and got the following error messages:`No zone found for linkId`. This error message is originally generated from _matsim\contribs\drt\src\main\java\org\matsim\contrib\drt\analysis\zonal\ZonalDemandAggregator.java_

After some investigations, there are two main reasons cause this issue:

- I think there is a bug in _matsim\contribs\drt\src\main\java\org\matsim\contrib\drt\analysis\zonal\DrtGridUtils.java_. There is no zones defined for some nodes in the network. 

```
public class DrtGridUtils {

	public static Map<String,Geometry> createGridFromNetwork(Network network, double cellsize){
		
		double[] boundingbox = NetworkUtils.getBoundingBox(network.getNodes().values());
		double minX = (Math.floor(boundingbox[0] / cellsize)*cellsize);
		double maxX = (Math.floor(boundingbox[2] / cellsize)*cellsize);
		double minY = (Math.floor(boundingbox[1] / cellsize)*cellsize);
		double maxY = (Math.floor(boundingbox[3] / cellsize)*cellsize);
		GeometryFactory gf = new GeometryFactory();
		Map<String,Geometry> grid = new HashMap<>();
		int cell = 0;
		for (double lx = minX;lx<maxX;lx +=cellsize ){
				
			for (double by = minY;by<maxY;by+=cellsize){
				cell++;
				Coordinate p1 = new Coordinate(lx, by);
				Coordinate p2 = new Coordinate(lx+cellsize, by);
				Coordinate p3 = new Coordinate(lx+cellsize, by+cellsize);
				Coordinate p4 = new Coordinate(lx, by+cellsize);
				Coordinate [] ca = {p1, p2, p3, p4, p1};
				Polygon p = new Polygon(gf.createLinearRing(ca), null, gf); 
				grid.put(cell+"", p);
			}
		}
		
		return grid;
```
In the code above, maxX and maxY are calculated by math.floor which returns the largest integer less than or equal to a given number. This means the nodes with the X,Y axis values greater than maxX, maxY will not fall inside of any zones created by this script. The solution here is either change math.floor to math.ceil for maxX and maxY (`double maxX = (Math.ceil(boundingbox[2] / cellsize)*cellsize); double maxY = (Math.ceil(boundingbox[3] / cellsize)*cellsize);`), or change conditions in for loop to `double lx = minX;lx<=maxX;lx +=cellsize` and `double by = minY;by<=maxY;by+=cellsize`. 

- The second one. See the following code in _getZoneForLinkId_ in  _matsim\contribs\drt\src\main\java\org\matsim\contrib\drt\analysis\zonal\DrtZonalSystem.java_ : 

```
		Point linkCoord = MGC.coord2Point(network.getLinks().get(linkId).getCoord());
		for (Entry<String, Geometry> e : zones.entrySet()) {
			if (e.getValue().contains(linkCoord)) {			    
				link2zone.put(linkId, e.getKey());
				return e.getKey();
			}
		}
```
Here, when checking if the _linkCoord_ is inside of a zone, if the _linkCoord_ is exactly on the edge of a zone, it will also generate this error message. For now, I can avoid this problem by changing some settings like cellsize when I run the simulation with a simple network. Thinking it would be nice if there is a method can handle this by assigning the linkId to one of the zones when the _linkCoord_ falls on the edge of a zone.

**Comment by jfbischoff** [comment]
Thanks for reporting, I will fix it in the next couple of hours.

**Comment by XXXinnnn** [comment]
Hi,
I have seen your changes in master, but I'm still running matsim and drt with 0.11.0-SNAPSHOT version. How can I get your changes?

**Comment by jfbischoff** [comment]
change the snapshot in your pom to 12.0.-SNAPSHOT , then you should be able to use the latest versions.

**Comment by XXXinnnn** [comment]
I have updated my POM to 12.0-SNAPSHOT, but I still got the same "None zone found for linkId" error. Seems the drt-12.0-SNAPSHOT is still old. Have you tested it after the merge?

**Comment by jfbischoff** [comment]
The snapshot should be up to date in a couple of hours, deployment takes some time.

**Comment by XXXinnnn** [comment]
Okay thanks a lot for your help! It is working now!
